In [1]:
import numpy as np

In [51]:
a = np.arange(5)

In [52]:
a

array([0, 1, 2, 3, 4])

In [53]:
b = a.reshape((2, -1))

ValueError: cannot reshape array of size 5 into shape (2,newaxis)

In [45]:
b

array([[0, 1],
       [2, 3]])

In [49]:
b[:,None]

array([[[0, 1]],

       [[2, 3]]])