In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(4, 6)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
np.pad(a, ((1,1), (1,1)), mode='edge')

array([[ 0,  0,  1,  2,  3,  4,  5,  5],
       [ 0,  0,  1,  2,  3,  4,  5,  5],
       [ 6,  6,  7,  8,  9, 10, 11, 11],
       [12, 12, 13, 14, 15, 16, 17, 17],
       [18, 18, 19, 20, 21, 22, 23, 23],
       [18, 18, 19, 20, 21, 22, 23, 23]])

In [5]:
line_mask = np.zeros(a.shape[1], dtype='bool')
line_mask

array([False, False, False, False, False, False])

In [7]:
line_mask[3] = True
line_mask

array([False, False, False,  True, False, False])

In [9]:
a[2,~line_mask].shape

(5,)