In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a = a.reshape((2,-1))

In [4]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
b = np.stack([a,a])

In [9]:
b.shape

(2, 2, 5)

In [12]:
a = a.reshape(-1)

In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.tile(a, 2).reshape(4,-1)

In [15]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])