In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import torch 
import os 
import pandas as pd

In [4]:
torch.cuda.is_available()

True

In [5]:
img_path = 'tests/00_test_img_input/train/images/'
labels_path = 'tests/00_test_img_input/train/gt.csv'

In [6]:
imgs = os.listdir(img_path)

In [7]:
labels_df = pd.read_csv(labels_path)

In [8]:
labels_df.head()

filename  x1   y1   x2  y2   x3  y3   x4  y4  x5  ...  x10  y10  x11  y11  \
0  00000.jpg  51   51  127  60  169  65  203  52  68  ...  193   84  156  144   
1  00001.jpg  21   20   36  18   57  19   80  25  23  ...   78   33   43   46   
2  00002.jpg  23  116   39  83   47  57   56  19  36  ...   62   31   91   86   
3  00003.jpg  29   18   63  25   84  32  105  34  38  ...   95   45   72   71   
4  00004.jpg  31   53   76  44  107  38  136  33  40  ...  129   49  111  105   

   x12  y12  x13  y13  x14  y14  
0   92  174  140  180  168  179  
1   31   61   45   66   60   65  
2  106  122  115  100  121   81  
3   46   83   63   87   75   89  
4   72  137  106  132  126  121  

[5 rows x 29 columns]

In [9]:
items = []
for i in range(len(imgs)):
    img = imgs[i]
    labels = labels_df.loc[labels_df['filename'] == img][labels_df.columns[2:]].values
    labels = torch.from_numpy(labels)
    items.append((os.path.join(img_path, img), labels[0]))

    

In [10]:
items[:5]

[('tests/00_test_img_input/train/images/00000.jpg',
  tensor([ 51, 127,  60, 169,  65, 203,  52,  68,  77,  85,  75, 110,  82, 160,
           87, 171,  79, 193,  84, 156, 144,  92, 174, 140, 180, 168, 179])),
 ('tests/00_test_img_input/train/images/00001.jpg',
  tensor([20, 36, 18, 57, 19, 80, 25, 23, 27, 34, 26, 40, 28, 59, 30, 68, 30, 78,
          33, 43, 46, 31, 61, 45, 66, 60, 65])),
 ('tests/00_test_img_input/train/images/00002.jpg',
  tensor([116,  39,  83,  47,  57,  56,  19,  36, 115,  40,  96,  47,  87,  59,
           60,  59,  41,  62,  31,  91,  86, 106, 122, 115, 100, 121,  81])),
 ('tests/00_test_img_input/train/images/00003.jpg',
  tensor([ 18,  63,  25,  84,  32, 105,  34,  38,  31,  48,  34,  59,  39,  79,
           44,  85,  43,  95,  45,  72,  71,  46,  83,  63,  87,  75,  89])),
 ('tests/00_test_img_input/train/images/00004.jpg',
  tensor([ 53,  76,  44, 107,  38, 136,  33,  40,  67,  52,  62,  73,  64, 104,
           58, 115,  50, 129,  49, 111, 105,  72, 137, 

In [11]:
y = labels_df.loc[labels_df['filename'] == imgs[0]][labels_df.columns[1:]]

In [12]:
y

x1  y1   x2  y2   x3  y3   x4  y4  x5  y5  ...  x10  y10  x11  y11  x12  \
0  51  51  127  60  169  65  203  52  68  77  ...  193   84  156  144   92   

   y12  x13  y13  x14  y14  
0  174  140  180  168  179  

[1 rows x 28 columns]

In [13]:
y.values

array([[ 51,  51, 127,  60, 169,  65, 203,  52,  68,  77,  85,  75, 110,
         82, 160,  87, 171,  79, 193,  84, 156, 144,  92, 174, 140, 180,
        168, 179]], dtype=int64)

In [14]:
y.values.shape

(1, 28)

In [15]:
items = []
for i in range(labels_df.shape[0]):
    columns = labels_df.columns
    filename = labels_df[columns[0]][i]
    labels = labels_df[labels_df.columns[2:]].values
    items.append((os.path.join(img_path, filename), labels[0]))

In [16]:
import pytorch_lightning as pl

In [17]:
import detection

In [20]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [22]:
#%tensorboard --logdir lightning_logs

In [23]:
detection.train_detector()

d:\venvs\CV\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
d:\venvs\CV\lib\site-packages\pytorch_lightning\utilities\model_summary\model_summary.py:452: A layer with UninitializedParameter was found. Thus, the total number of parameters detected may be inaccurate.

  | Name  | Type                | Params
----------------------------------------------
0 | model | FacesPointsDetector | 371 K 
----------------------------------------------
371 K     Trainable params
0         Non-trainable params
371 K     Total params
1.487     Total estimated model params size (MB)
d:\venvs\CV\lib\site-packa

Epoch 2: 100%|██████████| 300/300 [00:54<00:00,  5.54it/s, v_num=14, loss_step=30.60, loss_epoch=47.20]Epoch 2, Train_loss: 47.151


`Trainer.fit` stopped: `max_epochs=3` reached.


Epoch 2: 100%|██████████| 300/300 [00:54<00:00,  5.54it/s, v_num=14, loss_step=30.60, loss_epoch=47.20]


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
def vizualize(img, keypoints):
    

    