In [3]:
import numpy as np

In [4]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
exps = np.exp(a)
exps

array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03]])

In [6]:
norms = np.sum(exps, axis = 1)
norms = norms[:, None]
norms

array([[3.71828183e+00],
       [2.74745930e+01],
       [2.03011309e+02],
       [1.50006195e+03],
       [1.10840419e+04]])

In [7]:
# norms = [1,2]
normalized = exps / norms
normalized

array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858],
       [0.26894142, 0.73105858],
       [0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])

In [8]:
np.sum(normalized, axis = 0)

array([1.34470711, 3.65529289])

In [9]:
def SM(a):
    inputs = a.copy()
    inputs -= inputs.max()
    print(inputs.shape)
    exps = np.exp(inputs)
    print(exps.shape)
    norm_coefs = np.sum(exps, axis=1)[:,None]
    return np.divide(exps, norm_coefs)

In [10]:
a = np.array([[-264., -346.], [-130., 241.], [-745., -601.], [-662., -4.], [ 749.,  305.],
                  [ 716.,  485.],
                  [1004., -711.],
                  [ 512.,  682.],
                  [ 166.,  393.],
                  [-255.,   62.],                  [-753.,   36.],
                 [  15.,  765.],
                 [-682., -679.],
                 [ 847.,  538.],
                 [ 958.,  622.],
                 [-792.,  -35.],
                  [-449.,  608.],
                  [-609., -120.],
                  [-758.,  -28.],
                  [ 325.,  925.],
                  [-281., -114.],
                  [-582., -465.],
                  [ 861.,  721.],
                  [-949., -778.],
                  [ 827., -445.],
                 [-712., -449.],
                  [ 693.,  591.],
                  [-682., -310.],
                [ 181.,  954.],
                 [ -41., -299.],
                  [ 934., -393.],
                  [-626.,  240.]])

In [11]:
SM(a)

(32, 2)
(32, 2)


C:\Users\Андрей\AppData\Local\Temp\ipykernel_18348\3472492231.py:8: RuntimeWarning: invalid value encountered in divide
  return np.divide(exps, norm_coefs)


array([[            nan,             nan],
       [            nan,             nan],
       [            nan,             nan],
       [            nan,             nan],
       [1.00000000e+000, 1.49021879e-193],
       [1.00000000e+000, 4.76403211e-101],
       [1.00000000e+000, 0.00000000e+000],
       [1.47889751e-074, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [            nan,             nan],
       [            nan,             nan],
       [0.00000000e+000, 1.00000000e+000],
       [            nan,             nan],
       [1.00000000e+000, 6.35338381e-135],
       [1.00000000e+000, 1.19413680e-146],
       [            nan,             nan],
       [0.00000000e+000, 1.00000000e+000],
       [            nan,             nan],
       [            nan,             nan],
       [2.65039655e-261, 1.00000000e+000],
       [            nan,             nan],
       [            nan,             nan],
       [1.00000000e+000, 1.58042006e-061],
       [   

In [12]:
y_gt = np.array([[0., 0., 1., 0.], [0., 0., 1., 0.], [0., 1., 0., 0.]])
y_gt.shape

(3, 4)

In [13]:
target_indices = np.argmax(y_gt, axis=1)

In [14]:
y_pred = np.array([[0.33691088, 0.3064258 , 0.1339102 , 0.22275312], [0.24908269, 0.05323729, 0.21219856, 0.48548146],
                [0.28376126, 0.41721049, 0.09371058, 0.20531767]])

In [15]:
y_pred.shape

(3, 4)

In [16]:
probs = y_pred[(np.arange(3), target_indices)]
probs

array([0.1339102 , 0.21219856, 0.41721049])

In [17]:
loss = -np.mean((np.log(probs)))[None]

In [18]:
img = np.arange(25).reshape(5,5)
img = np.stack([img, img], axis=0)
img = np.stack([img, img], axis = 0)
kernel = np.array([[0, 1],[0, 0]])
kernel = np.stack([kernel, kernel], axis = 0)
kernel = np.stack([kernel, kernel, kernel], axis = 0)
res = np.zeros((img.shape[0],kernel.shape[0], img.shape[-2]- kernel.shape[-2]//2,img.shape[-1] - kernel.shape[-1]//2))
res.shape

(2, 3, 4, 4)

In [19]:
img.shape

(2, 2, 5, 5)

In [20]:
img[0]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [21]:
kernel

array([[[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]]],


       [[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]]],


       [[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]]]])

In [22]:
kernel.shape

(3, 2, 2, 2)

In [23]:
ext_img = img[:,None,...]
ext_img.shape

(2, 1, 2, 5, 5)

In [24]:
ext_kernel = kernel[None,...]
ext_kernel.shape

(1, 3, 2, 2, 2)

In [25]:
img = np.array([[[[ 205., 985., -846., -828., 1014.], [-290., -936., -226.,  433., -237.],
                        [-277.,  182., -816., -532.,  129.],
                        [-360.,   12.,  633., -154., -293.],
                        [ 105.,  374.,  581.,  706., -327.]]]])

kernel = np.array([[[[ 98., -431., 586.], [-139., -173., 191.], [-700., -46.,  725.]]]])

In [26]:
print(img.shape)
kernel.shape

(1, 1, 5, 5)


(1, 1, 3, 3)

In [27]:
ext_img = img[:,None,...]
print(ext_img.shape)

ext_kernel = kernel[None,...]
print(ext_kernel.shape)

(1, 1, 1, 5, 5)
(1, 1, 1, 3, 3)


In [28]:
res = np.zeros((img.shape[0],kernel.shape[0], img.shape[-2]- kernel.shape[-2] + 1,img.shape[-1] - kernel.shape[-1] + 1))

In [29]:
di = kernel.shape[-2]
dj = kernel.shape[-1]
for i in range(res.shape[-2]):
    for j in range(res.shape[-1]):
        # print(ext_img[...,i:i+di,j:j+dj])
        res[...,i,j] = np.sum(ext_kernel*ext_img[...,i:i+di,j:j+dj])
res[0,0]

array([[-1147201.,  -247711.,  1468599.],
       [  804094.,   124506.,  -765995.],
       [  -84376.,   140513.,  -568641.]])

In [30]:
np.pad(img, [[0,0],[0,0],[1,1],[2,2]]).shape

(1, 1, 7, 9)

In [31]:
img[0]

array([[[ 205.,  985., -846., -828., 1014.],
        [-290., -936., -226.,  433., -237.],
        [-277.,  182., -816., -532.,  129.],
        [-360.,   12.,  633., -154., -293.],
        [ 105.,  374.,  581.,  706., -327.]]])

In [32]:
kernel[0]

array([[[  98., -431.,  586.],
        [-139., -173.,  191.],
        [-700.,  -46.,  725.]]])

In [33]:
np.sum((kernel[0]*img[...,:kernel.shape[-2], :kernel.shape[-1]]))

-1147201.0

In [56]:
x = np.arange(54).reshape(2, 3,3,3)

In [57]:
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [58]:
x.shape

(2, 3, 3, 3)

In [59]:
xx = np.sum(x, axis = 0) #x.reshape(x.shape[0], -1)

In [61]:
xx.shape

(3, 3, 3)

In [62]:
np.sum(x.reshape(xx.shape[0], -1), axis = 1)

array([153, 477, 801])

In [101]:
size_1 = 4
size_2 = 8

In [102]:
x = np.arange(size_1*size_2).reshape(size_1, size_2)

In [103]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [94]:
p = 2

In [ ]:
x[]

In [105]:
x.reshape(-1, p, p)#[...,::2,:]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])