In [290]:
import numpy as np

In [291]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [292]:
exps = np.exp(a)
exps

array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03]])

In [293]:
norms = np.sum(exps, axis = 1)
norms = norms[:, None]
norms

array([[3.71828183e+00],
       [2.74745930e+01],
       [2.03011309e+02],
       [1.50006195e+03],
       [1.10840419e+04]])

In [294]:
# norms = [1,2]
normalized = exps / norms
normalized

array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858],
       [0.26894142, 0.73105858],
       [0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])

In [295]:
np.sum(normalized, axis = 0)

array([1.34470711, 3.65529289])

In [296]:
def SM(a):
    inputs = a.copy()
    inputs -= inputs.max()
    print(inputs.shape)
    exps = np.exp(inputs)
    print(exps.shape)
    norm_coefs = np.sum(exps, axis=1)[:,None]
    return np.divide(exps, norm_coefs)

In [297]:
a = np.array([[-264., -346.], [-130., 241.], [-745., -601.], [-662., -4.], [ 749.,  305.],
                  [ 716.,  485.],
                  [1004., -711.],
                  [ 512.,  682.],
                  [ 166.,  393.],
                  [-255.,   62.],                  [-753.,   36.],
                 [  15.,  765.],
                 [-682., -679.],
                 [ 847.,  538.],
                 [ 958.,  622.],
                 [-792.,  -35.],
                  [-449.,  608.],
                  [-609., -120.],
                  [-758.,  -28.],
                  [ 325.,  925.],
                  [-281., -114.],
                  [-582., -465.],
                  [ 861.,  721.],
                  [-949., -778.],
                  [ 827., -445.],
                 [-712., -449.],
                  [ 693.,  591.],
                  [-682., -310.],
                [ 181.,  954.],
                 [ -41., -299.],
                  [ 934., -393.],
                  [-626.,  240.]])

In [298]:
SM(a)

(32, 2)
(32, 2)


C:\Users\Андрей\AppData\Local\Temp\ipykernel_18540\3472492231.py:8: RuntimeWarning: invalid value encountered in divide
  return np.divide(exps, norm_coefs)


array([[            nan,             nan],
       [            nan,             nan],
       [            nan,             nan],
       [            nan,             nan],
       [1.00000000e+000, 1.49021879e-193],
       [1.00000000e+000, 4.76403211e-101],
       [1.00000000e+000, 0.00000000e+000],
       [1.47889751e-074, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [            nan,             nan],
       [            nan,             nan],
       [0.00000000e+000, 1.00000000e+000],
       [            nan,             nan],
       [1.00000000e+000, 6.35338381e-135],
       [1.00000000e+000, 1.19413680e-146],
       [            nan,             nan],
       [0.00000000e+000, 1.00000000e+000],
       [            nan,             nan],
       [            nan,             nan],
       [2.65039655e-261, 1.00000000e+000],
       [            nan,             nan],
       [            nan,             nan],
       [1.00000000e+000, 1.58042006e-061],
       [   

In [299]:
y_gt = np.array([[0., 0., 1., 0.], [0., 0., 1., 0.], [0., 1., 0., 0.]])
y_gt.shape

(3, 4)

In [300]:
target_indices = np.argmax(y_gt, axis=1)

In [301]:
y_pred = np.array([[0.33691088, 0.3064258 , 0.1339102 , 0.22275312], [0.24908269, 0.05323729, 0.21219856, 0.48548146],
                [0.28376126, 0.41721049, 0.09371058, 0.20531767]])

In [302]:
y_pred.shape

(3, 4)

In [303]:
probs = y_pred[(np.arange(3), target_indices)]
probs

array([0.1339102 , 0.21219856, 0.41721049])

In [304]:
loss = -np.mean((np.log(probs)))[None]

In [305]:
img = np.arange(25).reshape(5,5)
img = np.stack([img, img], axis=0)
img = np.stack([img, img], axis = 0)
kernel = np.array([[0, 1],[0, 0]])
kernel = np.stack([kernel, kernel], axis = 0)
kernel = np.stack([kernel, kernel, kernel], axis = 0)
res = np.zeros((img.shape[0],kernel.shape[0], img.shape[-2]- kernel.shape[-2]//2,img.shape[-1] - kernel.shape[-1]//2))
res.shape

(2, 3, 4, 4)

In [306]:
img.shape

(2, 2, 5, 5)

In [307]:
img[0]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [308]:
kernel

array([[[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]]],


       [[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]]],


       [[[0, 1],
         [0, 0]],

        [[0, 1],
         [0, 0]]]])

In [309]:
kernel.shape

(3, 2, 2, 2)

In [310]:
ext_img = img[:,None,...]
ext_img.shape

(2, 1, 2, 5, 5)

In [311]:
ext_kernel = kernel[None,...]
ext_kernel.shape

(1, 3, 2, 2, 2)

In [312]:
img = np.array([[[[ 205., 985., -846., -828., 1014.], [-290., -936., -226.,  433., -237.],
                        [-277.,  182., -816., -532.,  129.],
                        [-360.,   12.,  633., -154., -293.],
                        [ 105.,  374.,  581.,  706., -327.]]]])

kernel = np.array([[[[ 98., -431., 586.], [-139., -173., 191.], [-700., -46.,  725.]]]])

In [313]:
print(img.shape)
kernel.shape

(1, 1, 5, 5)


(1, 1, 3, 3)

In [314]:
ext_img = img[:,None,...]
print(ext_img.shape)

ext_kernel = kernel[None,...]
print(ext_kernel.shape)

(1, 1, 1, 5, 5)
(1, 1, 1, 3, 3)


In [315]:
res = np.zeros((img.shape[0],kernel.shape[0], img.shape[-2]- kernel.shape[-2] + 1,img.shape[-1] - kernel.shape[-1] + 1))

In [316]:
di = kernel.shape[-2]
dj = kernel.shape[-1]
for i in range(res.shape[-2]):
    for j in range(res.shape[-1]):
        # print(ext_img[...,i:i+di,j:j+dj])
        res[...,i,j] = np.sum(ext_kernel*ext_img[...,i:i+di,j:j+dj])
res[0,0]

array([[-1147201.,  -247711.,  1468599.],
       [  804094.,   124506.,  -765995.],
       [  -84376.,   140513.,  -568641.]])

In [317]:
np.pad(img, [[0,0],[0,0],[1,1],[2,2]]).shape

(1, 1, 7, 9)

In [318]:
img[0]

array([[[ 205.,  985., -846., -828., 1014.],
        [-290., -936., -226.,  433., -237.],
        [-277.,  182., -816., -532.,  129.],
        [-360.,   12.,  633., -154., -293.],
        [ 105.,  374.,  581.,  706., -327.]]])

In [319]:
kernel[0]

array([[[  98., -431.,  586.],
        [-139., -173.,  191.],
        [-700.,  -46.,  725.]]])

In [320]:
np.sum((kernel[0]*img[...,:kernel.shape[-2], :kernel.shape[-1]]))

-1147201.0

In [321]:
x = np.arange(54).reshape(2, 3,3,3)

In [322]:
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [323]:
x.shape

(2, 3, 3, 3)

In [324]:
xx = np.sum(x, axis = 0) #x.reshape(x.shape[0], -1)

In [325]:
xx.shape

(3, 3, 3)

In [326]:
np.sum(x.reshape(xx.shape[0], -1), axis = 1)

array([153, 477, 801])

In [327]:
size_1 = 4
size_2 = 8

In [328]:
x = np.arange(2*3*size_1*size_2).reshape(2,3,size_1, size_2)

In [329]:
p = 2

In [330]:
B = x.reshape((2, 3, -1, p, x.shape[-1]//p, p))  
C = B.transpose((0, 1, 2,4,3,5))#.reshape(2, 3, -1, p,p)

In [331]:
C.shape

(2, 3, 2, 4, 2, 2)

In [332]:
C[...,0,0] = 20

In [333]:
maxes = np.max(C, axis=(-1, -2))

In [334]:
#maxes = maxes.transpose((0, 1, 2,4,3,5)).reshape(x.shape[0], x.shape[1], x.shape[2]//p, x.shape[3]//p)
maxes.shape

ValueError: axes don't match array

In [ ]:
maxes

array([[[[ 20,  20,  20,  20],
         [ 25,  27,  29,  31]],

        [[ 41,  43,  45,  47],
         [ 57,  59,  61,  63]],

        [[ 73,  75,  77,  79],
         [ 89,  91,  93,  95]]],


       [[[105, 107, 109, 111],
         [121, 123, 125, 127]],

        [[137, 139, 141, 143],
         [153, 155, 157, 159]],

        [[169, 171, 173, 175],
         [185, 187, 189, 191]]]])

In [ ]:
block_means = np.sum(C, axis=(-1,-2)) / p**2

In [ ]:
block_means = block_means.reshape(x.shape[0], x.shape[1], x.shape[2]//p, x.shape[3]//p)

In [ ]:
block_means

array([[[[  9.5,  11. ,  12.5,  14. ],
         [ 21.5,  23. ,  24.5,  26. ]],

        [[ 33.5,  35. ,  36.5,  38. ],
         [ 45.5,  47. ,  48.5,  50. ]],

        [[ 57.5,  59. ,  60.5,  62. ],
         [ 69.5,  71. ,  72.5,  74. ]]],


       [[[ 81.5,  83. ,  84.5,  86. ],
         [ 93.5,  95. ,  96.5,  98. ]],

        [[105.5, 107. , 108.5, 110. ],
         [117.5, 119. , 120.5, 122. ]],

        [[129.5, 131. , 132.5, 134. ],
         [141.5, 143. , 144.5, 146. ]]]])

In [ ]:
flatten = C.reshape(-1, p*p)
flatten

array([[ 20,   1,   8,   9],
       [ 20,   3,  10,  11],
       [ 20,   5,  12,  13],
       [ 20,   7,  14,  15],
       [ 20,  17,  24,  25],
       [ 20,  19,  26,  27],
       [ 20,  21,  28,  29],
       [ 20,  23,  30,  31],
       [ 20,  33,  40,  41],
       [ 20,  35,  42,  43],
       [ 20,  37,  44,  45],
       [ 20,  39,  46,  47],
       [ 20,  49,  56,  57],
       [ 20,  51,  58,  59],
       [ 20,  53,  60,  61],
       [ 20,  55,  62,  63],
       [ 20,  65,  72,  73],
       [ 20,  67,  74,  75],
       [ 20,  69,  76,  77],
       [ 20,  71,  78,  79],
       [ 20,  81,  88,  89],
       [ 20,  83,  90,  91],
       [ 20,  85,  92,  93],
       [ 20,  87,  94,  95],
       [ 20,  97, 104, 105],
       [ 20,  99, 106, 107],
       [ 20, 101, 108, 109],
       [ 20, 103, 110, 111],
       [ 20, 113, 120, 121],
       [ 20, 115, 122, 123],
       [ 20, 117, 124, 125],
       [ 20, 119, 126, 127],
       [ 20, 129, 136, 137],
       [ 20, 131, 138, 139],
       [ 20, 1

In [ ]:
am = np.argmax(flatten, axis=-1)#.reshape(-1, 1)
am

array([0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3], dtype=int64)

In [ ]:
maxes_flatten = np.repeat(maxes.reshape(-1, 1), p*p, axis=-1)
zeros_flarren = np.zeros_like(maxes_flatten)
zeros_flarren[(np.arange(maxes_flatten.shape[0]), am)] = maxes_flatten[(np.arange(maxes_flatten.shape[0]), am)]

In [ ]:
zeros_flarren

array([[ 20,   0,   0,   0],
       [ 20,   0,   0,   0],
       [ 20,   0,   0,   0],
       [ 20,   0,   0,   0],
       [  0,   0,   0,  25],
       [  0,   0,   0,  27],
       [  0,   0,   0,  29],
       [  0,   0,   0,  31],
       [  0,   0,   0,  41],
       [  0,   0,   0,  43],
       [  0,   0,   0,  45],
       [  0,   0,   0,  47],
       [  0,   0,   0,  57],
       [  0,   0,   0,  59],
       [  0,   0,   0,  61],
       [  0,   0,   0,  63],
       [  0,   0,   0,  73],
       [  0,   0,   0,  75],
       [  0,   0,   0,  77],
       [  0,   0,   0,  79],
       [  0,   0,   0,  89],
       [  0,   0,   0,  91],
       [  0,   0,   0,  93],
       [  0,   0,   0,  95],
       [  0,   0,   0, 105],
       [  0,   0,   0, 107],
       [  0,   0,   0, 109],
       [  0,   0,   0, 111],
       [  0,   0,   0, 121],
       [  0,   0,   0, 123],
       [  0,   0,   0, 125],
       [  0,   0,   0, 127],
       [  0,   0,   0, 137],
       [  0,   0,   0, 139],
       [  0,  

In [ ]:
zeros_flarren.reshape(x.shape[0], x.shape[1], -1, x.shape[-1]//p, p, p).transpose(0, 1, 2, 4, 3, 5).reshape(x.shape[0], x.shape[1], x.shape[2], x.shape[3])

array([[[[ 20,   0,  20,   0,  20,   0,  20,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,  25,   0,  27,   0,  29,   0,  31]],

        [[  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,  41,   0,  43,   0,  45,   0,  47],
         [  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,  57,   0,  59,   0,  61,   0,  63]],

        [[  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,  73,   0,  75,   0,  77,   0,  79],
         [  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,  89,   0,  91,   0,  93,   0,  95]]],


       [[[  0,   0,   0,   0,   0,   0,   0,   0],
         [  0, 105,   0, 107,   0, 109,   0, 111],
         [  0,   0,   0,   0,   0,   0,   0,   0],
         [  0, 121,   0, 123,   0, 125,   0, 127]],

        [[  0,   0,   0,   0,   0,   0,   0,   0],
         [  0, 137,   0, 139,   0, 141,   0, 143],
         [  0,   0,   0,   0,   0,   0,   0,   0],
         [  0, 153,  

In [ ]:
x.shape

(2, 3, 4, 8)

In [ ]:
avg = 0
t = 0
for n in range(x.shape[0]):
    for h in range(x.shape[-2]):
        for w in range(x.shape[-1]):
            avg += x[n, 2, h, w]
            t+=1
avg = avg / t
std = 0
for n in range(x.shape[0]):
    for h in range(x.shape[-2]):
        for w in range(x.shape[-1]):
            std += (x[n, 2, h, w] - avg)**2
np.sqrt(std / t)

63.37931444880104

In [ ]:
x_tr = x.transpose(1, 0, 2, 3)
np.mean(x_tr.reshape(x_tr.shape[0], -1), axis=1)

array([ 53.75,  77.75, 101.75])

In [ ]:
np.std(x_tr.reshape(x_tr.shape[0], -1), axis=1)

array([46.57185309, 53.86035184, 63.37931445])

In [ ]:
x.shape

(2, 3, 4, 8)

In [ ]:
np.sum(x.reshape(x.shape[1], -1), axis = 0).shape

(64,)