In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
from skimage.io import imread
from scipy.ndimage import gaussian_filter
from skimage.metrics import peak_signal_noise_ratio

In [2]:
M = np.arange(25).reshape(5,5)
M

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
m = np.mean(M, axis=1)[:, None]
m

array([[ 2.],
       [ 7.],
       [12.],
       [17.],
       [22.]])

In [4]:
mm = m[:,0]

In [5]:
mm[:,None]

array([[ 2.],
       [ 7.],
       [12.],
       [17.],
       [22.]])

In [6]:
MM = M[...,None]
MM

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [7]:
MM[::2,::2]

array([[[ 0],
        [ 2],
        [ 4]],

       [[10],
        [12],
        [14]],

       [[20],
        [22],
        [24]]])

In [25]:
a = np.arange(8)
b = np.tile(a[:,None], 8)
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [26]:
bb = b.T
bb

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [27]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [28]:
a*np.cos(b + 1)*np.cos(bb + 1)

array([[  0.        ,  -0.2248451 ,  -1.06979046,  -1.05949547,
          0.61305333,   2.5939111 ,   2.44401076,  -0.55029803],
       [ -1.79876076,   1.55860371,   4.11982246,   2.99212898,
         -1.41654145,  -5.19443376,  -4.39227653,   0.90824068],
       [ -8.55832366,   7.00369818,  17.64153258,  12.29494332,
         -5.6164687 , -19.96178896, -16.41986665,   3.31301066],
       [ -8.47596373,   6.80029313,  16.82465928,  11.53574954,
         -5.19159138, -18.2006663 , -14.78350198,   2.94826024],
       [  4.90442665,  -3.895489  ,  -9.5479968 ,  -6.48948923,
          2.89671248,  10.07746807,   8.12643532,  -1.60964145],
       [ 20.7512888 , -16.38244492, -39.92357793, -26.98719486,
         11.98401608,  41.48671407,  33.29822901,  -6.56612603],
       [ 19.55208607, -15.37296787, -37.31787875, -25.13195336,
         11.12038518,  38.36535081,  30.69190489,  -6.03310419],
       [ -4.40238421,   3.45131459,   8.35454862,   5.61120497,
         -2.47637145,  -8.5219933

In [56]:
a = np.array([1,0,0,0,0,0,0,1, 3, 1, 4, 0, 0, 0])
changes_idx = (a[1:]-a[:-1]).nonzero()[0]
changes_idx

array([ 0,  6,  7,  8,  9, 10], dtype=int64)

In [57]:
for i in range(changes_idx.shape[0]):
    if changes_idx[i] == 0:
        val = a[changes_idx[i]]
        count = i + 1
    else:
        val = a[changes_idx[i]]
        count = changes_idx[i] - changes_idx[i-1]

    print(val, count)

1 1
0 6
1 1
3 1
1 1
4 1


In [60]:
count = 0
new_el = True
res = []
for i in range(a.shape[0]):
    val = a[i]
    if val != 0:
        res.append(val)

    else:
        if new_el:
            res.append(val)
            new_el = False
            count = 0
        count += 1
        if i + 1 == a.shape[0] or a[i+1] != 0:
            res.append(count)
            new_el = True
res

[1, 0, 6, 1, 3, 1, 4, 0, 3]

In [62]:
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7]])

In [73]:
c = np.zeros((2*b.shape[0], 2*b.shape[1]))
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [75]:
c[::2,::2] = b
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [6., 0., 6., 0., 6., 0., 6., 0., 6., 0., 6., 0., 6., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [78]:
c_rows = np.roll(c, (1, 0), axis=(0,1))
c_cols = np.roll(c, (0, 1), axis=(0,1))
c + c_rows

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0.],
       [2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0., 2., 0.],
       [3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0.],
       [3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0., 3., 0.],
       [4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0.],
       [4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0., 4., 0.],
       [5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0.],
       [5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0., 5., 0.],
       [6., 0., 6., 0., 6., 0., 6., 0., 6., 0., 6., 0., 6., 0., 6., 0.],
       [6., 0., 6., 0., 6., 0., 6., 0., 6., 0., 6.,

In [80]:
c_cols = np.roll(c+c_rows, (0, 1), axis=(0,1))
c + c_rows + c_cols

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,